### ISSUE TITLE
Code of Conduct: Selection and Reporting Method

### ISSUE THREAD

**Issue by jorydotcom** [EcmaTC53/admin#1]
Per our meeting discussion, we would like to evaluate adopting a Code of Conduct for TC53. Here are a couple of options to consider (please comment with others you'd like to discuss):

* Adopt the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct)
* Adopt or modify TC39's [Code of Conduct](https://tc39.github.io/code-of-conduct/)
* Create a bespoke Code of Conduct

Also, I reached out to the TC39 CoC team (full disclosure: I lead that group) to find out if they would be interested/able to support us from a response perspective. The easiest path to get started would likely be to set up a reporting email like tc53-conduct-report@ and have that go to the TC39 team. Initial feedback is positive on that approach.

**Comment by boazsender** [comment]
+1 to adopting the TC39 CoC and reporting structure since they already include reference to the Ecma bylaws, and fit into the existing reporting structure.

Does the TC39 CoC team need any additional help with managing and responding to conduct reports? I would be available to support the team, especially as it pertains to TC53, and any extra load that comes from that.

Thanks @jorydotcom!

**Comment by lprader** [comment]
(sorry, weird mouse freakout there led to me unassigning and reassigning this to Jory)

Another +1 to adopting the TC39 CoC!

**Comment by jorydotcom** [comment]
@boazsender @lprader Thank you both v. much!

I spoke with the TC39 CoC group today and they are very amenable to supporting us here. To do that though, they want to make it as clear as possible (for us and for community participants) how this will work. Their initial feedback is:
1. They would need us to adopt the TC39 CoC as-is (which seems very acceptable to us)
1. They would like us to provide a TC53 representative(s) for moderation/mediation discussion in order to provide context (@boazsender, yes please!!)
1. They would like to know whether TC53 expects to have oversight of the group in the way TC39 does (with regard to appointment/approval of CoC group members specifically). 
1. Perhaps a clarification of above, they would like to ensure that TC53 is comfortable with the authority of the _CoC group_ performing this task moreso than the specific individuals

any other thoughts or questions to bring up? If no, I can draft some sample policy here.

**Comment by boazsender** [comment]
Happy to be that rep. Thanks @jorydotcom!

**Comment by dtex** [comment]
I see the CoC was added [here](4180a7c1a0d05ec719f5f532d5378258b7c356f0), and communicated to the group per the notes from our October, 2019 plenary meeting (tc53-2019-040.doc) so I'm closing this.
