### ISSUE TITLE
TC53 JSConfUS Participation

### ISSUE THREAD

**Issue by jorydotcom** [EcmaTC53/admin#2]
@dtex @phoddie and others agree JSConfUS could be a great place to present about our work to the broader JS community.

Relevant links:
Dates: Aug. 12-14, Carlsbad, CA
[CFP Link](https://2019.jsconf.us/call-for-proposals/#selection-process)
[Website](https://2019.jsconf.us/)

Anyone interested in speaking, or perhaps doing a panel? We can use this issue to organize and draft a CFP Response. There are often other opportunities, in the past @rwaldron @HipsterBrown @dtex etc have done a nodebots activity as well.

**CFP DEADLINE IS MARCH 11**

**Comment by jorydotcom** [comment]
Deadline has passed! @phoddie @lprader did ya'll end up submitting a talk? please post and update and close! 👍

**Comment by phoddie** [comment]
Yes, we submitted a proposal for a talk from Moddable that is built around TC53 and the related work going on today in embedded JavaScript. The idea is to have different people talk about their company's efforts and how those relate to TC53. If we are fortunate enough to have it accepted, we'll have a lot about.  If not, well... we tried.
